### ISSUE TITLE
Feature Request - Allow Home Videos libraries and add as random type for blocks

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#11]
I'd like to be able to pepper commercial breaks into my blocks. I have a bunch of old commercials and random videos in my plex library under a home video type. I believe the best way to accomplish this would be if I were able to scan them into the database and add them as random types (like the random TV show or movie by genre) as a block entry.

**Comment by amazingr4b** [comment]
I was already thinking about adding something like this, so this one is getting marked as in progress. I havent decided how best to handle the playback injection, but I'm kicking around a few ideas. Might start with it being an item that can be added blocks as a test like you mentioned. So far the plan is to use a home videos library that is populated with commercials or commercial type videos. It is scanned and saved in a table that is then picked from for the inbetween playback. I already have the scanning and saving into a table bit added to the lastest updatedb script that will get posted later today.

**Comment by amazingr4b** [comment]
I'm thinking <a href="https://youtu.be/2i8dG5mHhGk">this is how it is going to go.</a>

**Comment by amazingr4b** [comment]
I expanded this a little bit. <a href ="https://youtu.be/snRMw1wFeW0">Now you can also add random commercials and prerolls to a block.</a> Clips of any length can be used, and as is you wont have the ability to specify a specif clip. Commercials will be pulled from a commercials library, prerolls from a preroll one.

**Comment by amazingr4b** [comment]
This has been expanded upon a little more. Now besides being able to add a commercial or preroll, you can specify a specific preroll or commercial by adding "preroll." or "commercial." in front of a title. Example: "preroll.freddy mercury preroll" 
Additionally, a new interrupt option has been added for those times when you need a beer or a bathroom break: commercial break. You can interrupt the currently playing feature by using the commercialbreak command, and it will play x number of commercials before returning to where you left off in the program. The number of commercials defaults to 2, but that can be changed as well. These updates will be part of a pending update that is currently testing. It is worth remembering that anything can be in the preroll or commercials sections. The system will wait for that video to complete before proceeding, meaning if you put a longish video in a commercial or preroll, it will not be cut off after a period of time.
