### ISSUE TITLE
Feature Request - Holiday Mode

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#12]
Note: This may require manual tagging of holiday movies and tv episodes within the Plex Server

Like normal mode, except only holiday movies and holiday tv show episodes are played. Advanced feature, it overrides episodes in existing blocks to force holiday episodes.

**Comment by amazingr4b** [comment]
For movies you can already do this. You can add custom genres using the addgenremovie action, and then use those genres in random selection options. For TV shows you could do it on a per show basis in similar fashion, but not so much on a per episode basis. The holiday part might be a little tough. There are many, and not everyone observes the same ones. I'm thinking maybe a way to keep track of specific episodes by some custom tag that can then be used as part of some custom holiday mode is the way to go. I'll mark this for future enhancement work once some other things are knocked out.

**Comment by amazingr4b** [comment]
This one is done, pending testing. The way it will work is as follows:  
You need to add holidays using - addholiday holidaytitle  
title can be a movie or a specific TV show episode(formatted showname:ssn:ep example psych:2:10)
if you have not previously added the holiday, it will be added to the holidays table. If it already exists it the desired item will be added to the list of items associated with the holiday.  
to enable holiday mode, the command is:
enableholiday holiday.holidayname
holiday. is the identifier, and holidayname must exist. 
When enabled, holiday mode will play random items associated with the specified holiday.

**Comment by amazingr4b** [comment]
Additional actions:
removefromholiday holiday title
removes the given title associated with the given holiday.
example: 
removefromholiday xmas "brooklyn nine-nine:1:10"

removeholiday holiday
removes the given holiday and all associations to it
example:
removeholiday xmas

checkholidays
lists the user created holidays and items associated with it
example:
checkholidays
