### ISSUE TITLE
Commercials removed from plex server aren't removed from commercials database when updated

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#14]
As it says above, it looks like files removed from the commercials folder and plex server database aren't being removed from the database here, even after running the update script with 'getcommercials'. I pulled a few files from the folder because they weren't really commercials (a couple of prerolls and a new year's 1990 news broadcast), but piplaystate locks up when it hits a file it can't find. The output is below, when this happens it needs to be forced down and restarted manually.

Doing a session check.
Stopped
Traceback (most recent call last):
  File "/home/pi/hasystem//system.py", line 5168, in <module>
    playcommercial("none")
  File "/home/pi/hasystem//system.py", line 2611, in playcommercial
    commercial = plex.library.section('Commercials').get(show)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 129, in get
    return utils.findItem(self.server, path, title)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/utils.py", line 162, in findItem
    raise NotFound('Unable to find item: %s' % title)
plexapi.exceptions.NotFound: Unable to find item: Headline News - from January 1, 1990!

**Comment by amazingr4b** [comment]
The updatedb file has been updated so the preroll and commercial get functions now purges the data in the table before it gets the data. This will remove the removed items and also update any that were changed in plex between scans. This same action was added recently for the movies and tv gets as well.
