### ISSUE TITLE
upddatedb_pi.py crashes at start of movie scan

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#16]
I did an updddatedb_pi.py all to refresh my database and after getting through the TV show scan, it crashed with the following:

Part 1 done. Moving on.
TV Files Cleaned
TV entries checked.
Traceback (most recent call last):
  File "upddatedb_pi.py", line 1288, in <module>
    getshows()
  File "upddatedb_pi.py", line 139, in getshows
    duration = duration[1]
IndexError: list index out of range

**Comment by amazingr4b** [comment]
You need to check your library. That failure is caused by something that has no duration like an unmatched show or something with some other problem.
