### ISSUE TITLE
Feature request: Output queue as a continually-updated playlist

### ISSUE THREAD

**Issue by Joshfindit** [amazingr4b/TBN-Plex#18]
After configuration it would be easy to open the app on the ipad, iphone, laptop, or whatever is most convenient, and select a TBN playlist to watch what's scheduled for that time.

**Comment by amazingr4b** [comment]
I'm not following what you are trying to request. What app are you referring to?

**Comment by Joshfindit** [comment]
Apologies, I may have glossed over too many details.

Currently, TBN-Plex seems to work directly with the player, creating block programming and then pushing it in real time, usually to a TV, but presumably could be to any player. (Correct me if I'm wrong)

Since TBN-Plex is using it's own database and storing the block-based programming, the suggestion is to allow that programming to be "pushed" in to playlists on the Plex server.

To use this example: https://www.youtube.com/watch?v=a5lOLjzunMQ&feature=youtu.be

`crime_tv_block` could be pushed to a playlist on the Plex server called "Crime TV Block", and then on Plex/Web, or the Plex Mobile app, the user would simply open the playlists and choose "Crime TV Block" to watch the first item in that block.

The second part of the request is to make these 'real-time updatable'.
Let's take for example a playlist on the Plex server called "TBN-Plex-Now" and a "friday_night" block. On thursday, "TBN-Plex-Now" could be empty, but then on Friday it's populated by the friday_night block.

On Plex/Web, PHT, or a mobile app, the user selects the "TBN-Plex-Now" playlist, and it plays the content that is up now according to TBN-Plex.


*Side bonus, this allows for commercial breaks, scheduling, and all sort of the cool parts of TBN-Plex on any 'vanilla' Plex client.

**Comment by MoeFwacky** [comment]
Currently, as is my understanding, this script doesn't touch the plex client's playlists. Instead it just uses the API to play content according to the block. If scheduled, this eliminates the need for any interaction with Plex menus. Wouldn't this functionality just complicate how the script interacts with Plex? 

Now I'm not the developer here, so take with that what you will, but if you're wanting to output to multiple devices, I would suggest maybe configuring the client Pi to output to an RTMP stream, either directly or by plugging it in through a capture card in another machine. From there you can access the RTMP stream from any device on your network using VLC player or another player of your choice.

Now, I would love a web gui interface for this script that included data like the active block, episodes that are coming up in the block, what's playing now, and maybe some basic commands like mute, skip to next program and things like that, which I could check from any device on the network, but that's probably a different kind of request.

**Comment by amazingr4b** [comment]
The scripts can control any client that is recognized by the plex api as a client. If the device is not recognized as a client, like a chromecast, there is nothing I can do to change that.

As far as the rest of it, the block packages that can be created with this setup are not the same as a playlist in plex. While you could use the API access to read what is in a block and convert it to some type of playlist, that is not something I have interest in adding at this time. These scripts are designed to run independent of the plexweb or client gui for automation purposes.  

A simple GUI is on the agenda, but I'm no web guru, so I wouldn't expect anything fancy.

**Comment by Joshfindit** [comment]
Any chance I can convinced you to add a function that takes the block name, then outputs the Plex IDs (and maybe names) starting with what's up next?

**Comment by amazingr4b** [comment]
Not sure what you mean by plex ids... Did you try using the explainblock command? When a block is active it tells you what item is next, and if it is a show it will also specify what episode that is:

pi@raspberrypi:~ $ explainblock
The crime_block plays the following:
scorpion
criminal minds
memphis beat
psych
numb3rs
elementary
The Mentalist
Almost Human


Item 1, scorpion is next.
Up next we have scorpion, Season 2, Episode 8, Area 51
pi@raspberrypi:~ $

.... When you specify a block you get similar output, only without the details on which item is next. I suppose we could add a command to get that for a specific block, but if there is one the output will be  similar to the "Item1...." portion from the example above.

**Comment by amazingr4b** [comment]
The feature requested in the title of this post has been added. Testing Demo: <a href = "https://www.youtube.com/watch?v=ZXcXnC0_5QE">https://www.youtube.com/watch?v=ZXcXnC0_5QE</a>

As far as having it update the playlist in plex when something like a block package is active, that may or may not be added, I'm still thinking about it.

**Comment by amazingr4b** [comment]
<a href="https://youtu.be/OpWJkucX9Xo"> closing this one.</a>
