### ISSUE TITLE
[Feature Request] Show Position Backup and Restore

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#19]
I don't know if this is entirely necessary anymore, but in the past some updates needed a fresh database, and I find that installing from scratch tends to be the most reliable method of updating in terms of stability. So with that, I'm requesting a tool that would allow saving all of the episode positions for all the shows in the database to a backup file, and in the same vein a tool that restores said positions after a new database has been generated.

**Comment by amazingr4b** [comment]
Shouldn't need to worry about making a new database in the future, but ... You mean the timeline position where you left off in a specific episode, or what episode is up next for any given series? If the former, that is grabbed from your plex server as needed, if the latter, that's doable.

**Comment by MoeFwacky** [comment]
Yeah, I'm looking for the latter for instances when i might need to wipe the database for a reinstall or moving the script to different hardware.

**Comment by amazingr4b** [comment]
This has been added to the posted version. If used, a file "tvcounts" is created. To restore from it that file needs to be placed in the "hasystem/" directory. 

Usage example:

pi@raspberrypi:~/hasystem $ python system.py backuptvcounts
100.0%
TV Counts have been backed up to: "/home/pi/hasystem/tvcounts".
pi@raspberrypi:~/hasystem $ python system.py restoretvcounts

Do you want to overwrite existing entries if any exit?

Yes or No?: no
100.0%
TV Counts have been restored.

pi@raspberrypi:~/hasystem $
