### ISSUE TITLE
Commercial Mode database update doesn't update entries that have had their filenames changed

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#24]
I ran into some special character errors with the file names of several of the commercials, and in my haste to get it working, I just renamed every file with any special characters at all. However, updating the commercials database doesn't update those entries and I get errors like one below

```
Stopped
Traceback (most recent call last):
  File "/home/pi/hasystem//system.py", line 7422, in <module>
    startnextprogram()
  File "/home/pi/hasystem//system.py", line 6674, in startnextprogram
    playcommercial("none")
  File "/home/pi/hasystem//system.py", line 3821, in playcommercial
    commercial = plex.library.section('Commercials').get(show)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 129, in get
    return utils.findItem(self.server, path, title)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/utils.py", line 162, in findItem
    raise NotFound('Unable to find item: %s' % title)
plexapi.exceptions.NotFound: Unable to find item: Commercial - But I''m Drinking Milk - Boy Talks Down Ruffians
```
and the file in my commercials folder is:
`Commercial - But Im Drinking Milk - Boy Talks Down Ruffians.flv`

**Comment by amazingr4b** [comment]
what is the name shown in your plex web for the item? I'll add a couple lines to the update file to delete the entries in that table before it rescans it. Having old garbage data in it will cause problems like that, and odds are its pulled a random bad entry instead of a good one for that random commercial request.

**Comment by MoeFwacky** [comment]
The plex server title matches the filename:

`Commercial - But Im Drinking Milk - Boy Talks Down Ruffians`

There are a handful that this occurs with, but I believe they're all the same situation of me renaming the files. There may be a couple that were removed as well, but I haven't come across one in an error I can paste.

**Comment by amazingr4b** [comment]
The upddated_db.py file I posted yesterday should fix that. update commercials using that version, and only good data will be in that table.
