### ISSUE TITLE
Schedules not working with most recent update

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#29]
I updated yesterday, and again today and the scheduled shows stopped working. I even cleared and re-entered the scheduled items to be sure. I checked the cronlog and the schedule script is running every minute.

```
Nov 30 19:29:01 BAD-HORSE /USR/SBIN/CRON[8061]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Nov 30 19:30:01 BAD-HORSE /USR/SBIN/CRON[8064]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
Nov 30 19:31:01 BAD-HORSE /USR/SBIN/CRON[8075]: (pi) CMD (python /home/pi/hasystem/tbn_schedule.py >/dev/null 2>&1 &)
```

And the item schedule to play during that time did not fire off
```
Action: futurama;
Time: 7:30 PM
Day: weekdays
```

I also had another item scheduled for the day (instead of weekdays) a bit later which also did not start.

```
Action: archer (2009);
Time: 8:00 PM
Day: wednesday
```

Not sure what the problem is, or if there's something I can do on my end to correct it. Let me know if you need any more data.

**Comment by amazingr4b** [comment]
I added a issue template with a bunch of questions for these type issues. Open a new issue and fill in all the bug questions.
