### ISSUE TITLE
Random movie in block not playing

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#4]
What it sounds like. some blocks have random movies in them don't play the movie. The random movie listing shows when 'explainblock' is run, but it skips it entirely. My plex server Alerts don't show any attempt to play a movie.

**Comment by amazingr4b** [comment]
Post what the explainblock outputs so I can see what it has.

**Comment by MoeFwacky** [comment]
Here's the block output for today's which set with a cron job to start at 4pm

The tuesday_d plays the following:
A random drama movie
King of the Hill
Futurama
The Simpsons

And here's the activity log from my plex server starting at 4pm

4:01 PM Moe Fwacky started playing King of the Hill - Hank's Unmentionable Problem on RasPlex.
4:24 PM Moe Fwacky started playing Futurama - Futurama - 05.04 - Futurama Into the Wild Green Yonder on RasPlex.
5:53 PM Moe Fwacky started playing The Simpsons - Bart the General on RasPlex.

**Comment by amazingr4b** [comment]
From there it looks right. Get the latest system.py file. A few of the fixes I did had to do with random movie playback. If it still doesn't work do: 
setplaymode to that block and then do a whatupnext and idtonightsmovie and post the output. You might need to do a restartblock if you previously interrupted that block.

**Comment by MoeFwacky** [comment]
It looks like the new update did the trick. I believe we can call this one closed.

**Comment by amazingr4b** [comment]
I'm going to repoen this one for now. I think there is still an issue I need to fix where it is occasionally putting a blank item in the db instead of a real one, which is causing some things to give blank output when that happens like idtonightsmovie.

**Comment by amazingr4b** [comment]
This has been addressed. Closing this one again.
